# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chunk_pb2 as chunk__pb2


class FileServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.upload_chunk_stream = channel.stream_unary(
        '/FileServer/upload_chunk_stream',
        request_serializer=chunk__pb2.Chunk.SerializeToString,
        response_deserializer=chunk__pb2.Reply.FromString,
        )
    self.upload_single_chunk = channel.unary_unary(
        '/FileServer/upload_single_chunk',
        request_serializer=chunk__pb2.Chunk.SerializeToString,
        response_deserializer=chunk__pb2.Reply.FromString,
        )
    self.download_chunk_stream = channel.unary_stream(
        '/FileServer/download_chunk_stream',
        request_serializer=chunk__pb2.Request.SerializeToString,
        response_deserializer=chunk__pb2.Chunk.FromString,
        )
    self.get_available_memory_bytes = channel.unary_unary(
        '/FileServer/get_available_memory_bytes',
        request_serializer=chunk__pb2.Empty_request.SerializeToString,
        response_deserializer=chunk__pb2.Reply_double.FromString,
        )
    self.get_stored_hashes_list_iterator = channel.unary_stream(
        '/FileServer/get_stored_hashes_list_iterator',
        request_serializer=chunk__pb2.Empty_request.SerializeToString,
        response_deserializer=chunk__pb2.Reply_string.FromString,
        )
    self.hash_id_exists_in_memory = channel.unary_unary(
        '/FileServer/hash_id_exists_in_memory',
        request_serializer=chunk__pb2.Request.SerializeToString,
        response_deserializer=chunk__pb2.Reply.FromString,
        )


class FileServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def upload_chunk_stream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload_single_chunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download_chunk_stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_available_memory_bytes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_stored_hashes_list_iterator(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def hash_id_exists_in_memory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'upload_chunk_stream': grpc.stream_unary_rpc_method_handler(
          servicer.upload_chunk_stream,
          request_deserializer=chunk__pb2.Chunk.FromString,
          response_serializer=chunk__pb2.Reply.SerializeToString,
      ),
      'upload_single_chunk': grpc.unary_unary_rpc_method_handler(
          servicer.upload_single_chunk,
          request_deserializer=chunk__pb2.Chunk.FromString,
          response_serializer=chunk__pb2.Reply.SerializeToString,
      ),
      'download_chunk_stream': grpc.unary_stream_rpc_method_handler(
          servicer.download_chunk_stream,
          request_deserializer=chunk__pb2.Request.FromString,
          response_serializer=chunk__pb2.Chunk.SerializeToString,
      ),
      'get_available_memory_bytes': grpc.unary_unary_rpc_method_handler(
          servicer.get_available_memory_bytes,
          request_deserializer=chunk__pb2.Empty_request.FromString,
          response_serializer=chunk__pb2.Reply_double.SerializeToString,
      ),
      'get_stored_hashes_list_iterator': grpc.unary_stream_rpc_method_handler(
          servicer.get_stored_hashes_list_iterator,
          request_deserializer=chunk__pb2.Empty_request.FromString,
          response_serializer=chunk__pb2.Reply_string.SerializeToString,
      ),
      'hash_id_exists_in_memory': grpc.unary_unary_rpc_method_handler(
          servicer.hash_id_exists_in_memory,
          request_deserializer=chunk__pb2.Request.FromString,
          response_serializer=chunk__pb2.Reply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
